name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build - and - deploy:
    runs - on: ubuntu - latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置 Node.js
        uses: actions/setup - node@v4
        with:
          node - version: 20
          cache: 'npm'  # 基于 package - lock.json 缓存

      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm install

      - name: 构建项目
        run: pnpm build:client

      - name: 部署到 GitHub Pages
        uses: JamesIves/github - pages - deploy - action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh - pages
          FOLDER: dist
